//! Integration test for `DocxDocument::rag_chunks()` against a *real*
//! Word-compatible DOCX fixture (`tests/fixtures/quarterly_report.docx`),
//! generated by an independent OOXML producer (python-docx).
//!
//! Unlike the in-memory builders used elsewhere in the suite, this fixture
//! carries the full namespace soup, a real `styles.xml` (Normal + Heading
//! styles with `outlineLvl`), and a real `numbering.xml`. Crucially its list
//! items use Word's built-in "List Bullet" *style* — the numbering lives on
//! the style, not on the paragraph — which is the dominant real-world list
//! pattern. The chunk text is asserted exactly, not by length or presence.

use oxidize_docx::pipeline::{HeadingContext, RagChunk};
use oxidize_docx::DocxDocument;

fn fixture_path() -> String {
    format!(
        "{}/tests/fixtures/quarterly_report.docx",
        env!("CARGO_MANIFEST_DIR")
    )
}

#[test]
fn rag_chunks_over_real_fixture_produces_exact_heading_scoped_chunks() {
    let doc = DocxDocument::open(fixture_path()).expect("fixture must open");
    let chunks: Vec<RagChunk> = doc.rag_chunks().expect("rag_chunks must succeed");

    // Two heading-scoped chunks: H1 section and H2 section.
    assert_eq!(chunks.len(), 2, "expected one chunk per heading section");

    // --- Chunk 0: under "Quarterly Report" (H1) ---
    let c0 = &chunks[0];
    assert_eq!(
        c0.text,
        "Quarterly Report\n\nRevenue grew across all regions this quarter."
    );
    assert_eq!(c0.element_types, vec!["heading", "paragraph"]);
    assert_eq!(c0.paragraph_indices, vec![0, 1]);
    assert_eq!(
        c0.heading_context,
        vec![HeadingContext {
            level: 1,
            text: "Quarterly Report".into(),
        }]
    );
    assert!(!c0.is_oversized);
    // 9 words → ceil(9 * 1.5) = 14.
    assert_eq!(c0.token_estimate, 14);

    // --- Chunk 1: under "Regional Breakdown" (H2, nested in H1) ---
    // The two "List Bullet"-styled paragraphs MUST surface as list items
    // (their numbering is inherited from the style, not a direct numPr).
    let c1 = &chunks[1];
    assert_eq!(
        c1.text,
        "Regional Breakdown\n\n\
         The strongest growth came from the following areas.\n\n\
         North America led with double-digit gains.\n\n\
         Europe followed close behind."
    );
    assert_eq!(
        c1.element_types,
        vec!["heading", "paragraph", "list_item", "list_item"],
        "List Bullet paragraphs must classify as list items via style numPr"
    );
    assert_eq!(c1.paragraph_indices, vec![2, 3, 4, 5]);
    assert_eq!(
        c1.heading_context,
        vec![
            HeadingContext {
                level: 1,
                text: "Quarterly Report".into(),
            },
            HeadingContext {
                level: 2,
                text: "Regional Breakdown".into(),
            },
        ]
    );
    assert!(!c1.is_oversized);
    // 20 words → ceil(20 * 1.5) = 30.
    assert_eq!(c1.token_estimate, 30);
}
